### PR TITLE
add composer script to build phar

### PR DESCRIPTION
**Pull request by glensc**
i think keeping binary in repo is wrong, repo size grows and i may wish to run from source only
the phar should be uploaded on each release, so people get pre built phar files from released versions.

so  this PR adds composer script to build phar, also removes phar from repository, the needed composer deps for box are added to composer.json and excluded from box.json

also reorganized readme so that "not interesting stuff" like compiling phar is at the bottom

also removed osx from readme, works on linux, and should work on windows too, just need to use `--db-path` if sqlite file not found automatically.

ps: don't forget to upload last .phar to existing release page ;)

### CODE REVIEW

**Comment by glensc** [comment]
@edderrd this can be merged

**Comment by edderrd** [comment]
@glensc thanks!

**Comment by glensc** [comment]
seems you still forgot to upload the phar?

https://github.com/edderrd/skype-logs/releases/tag/1.0.0 should have "edit release" button where you can do the upload

**Comment by edderrd** [comment]
Yup, now is [available](https://github.com/edderrd/skype-logs/releases/tag/1.1.0)

**Pull request merged**
