### PR TITLE
some refactor and add new commands

### PR DESCRIPTION
**Pull request by glensc**
... see individual commits for details

i'm publishing my changes, as i got my needed task done.
i might improve in the future, then can create more specific PR

### CODE REVIEW

**Comment by glensc** [comment]
don't hurry with merging this, i might have more commits coming

however, would like to hear some feedback indeed!

**Comment by edderrd** [comment]
Great new features!, please let me know when you're finished :+1:

**Comment by glensc** [comment]
rebased against master, i guess it's better to merge this as is now

**Comment by edderrd** [comment]
could you squash those commits into one

**Comment by glensc** [comment]
you can do that yourself with git merge --squash, but i personally like to preserve each commit, the git annotate would be more meaningful

**Comment by edderrd** [comment]
Will maintain the log for future reference

**Pull request merged**
