### PR TITLE
skip unsafe characters, at least on windows

### PR DESCRIPTION
**Pull request by glensc**
the error being:

```
PHP Warning:  fopen(skype-log-19:blablbla@thread.skype.csv): failed to open stream: Protocol error in phar:///vagrant/skype-logs.phar/src/Command/ExportByChatCommand.php on line 143
```

### CODE REVIEW

**Comment by glensc** [comment]
have you considered adding me as Collabrator, so could merge in things more easily?

**Review by edderrd — CHANGES_REQUESTED** [review]
It have more spaces/tabs that it should

**Comment by glensc** [comment]
@edderrd fixed indent style. however i stil can't merge, and shows i'm contributor not collaborator.

**Review by edderrd — APPROVED** [review]

**Comment by edderrd** [comment]
it seems that not directly on master https://help.github.com/articles/permission-levels-for-a-user-account-repository/

**Pull request merged**
